### ISSUE TITLE
Fechas no amigables en algunos dias

### ISSUE THREAD

**Issue by brujua** [agrup/Sistema-Planta-Piloto#164]
Deberian escribirse en algunos lados como
Martes 5 de agosto 2018

setlocale(LC_TIME, 'spanish');
        Carbon::setUtf8(true);

$fechaC = Carbon::createFromFormat('Y-m-d',$fecha);

$fechaC->formatLocalized('Insertar formato que corresponda ej: %A da el dia de la semana);

**Comment by woini2727** [comment]
solved
